apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-reverse-proxy
  name: proxy-svc
spec:
  selector:
    app: udagram-reverse-proxy
  ports:
    - name: "80"
      port: 80
      targetPort: 80
